### ISSUE TITLE
How do you do the Occupancy Sensors?

### ISSUE THREAD

**Issue by KristopherKubicki** [etsinko/ha-config#1]
Can you post the config for the occupancy sensors?

**Comment by etsinko** [comment]
@KristopherKubicki are you talking about this group?
```yaml
occupancy_sensors:
  name: Occupancy Sensors
  view: no
  entities:
    - binary_sensor.basement_occupancy
    - binary_sensor.loft_occupancy
    - binary_sensor.main_floor_occupancy
    - binary_sensor.master_bedroom_occupancy
    - binary_sensor.upstairs_occupancy
```
These are provided by `ecobee` platform. Basically each ecobee temperature sensor has motion detectors in them which stay on for about 20 minutes after motion has been detected. I have a few of them at different locations.
